theme: jekyll-theme-minimal
title: Rosetta Martin
description: >-
  San Diego State University graduate. Inquisitive learner. Lover of languages,
  both human and computer.
  <br><br>
  I am educated in both computer science and linguistics, and have completed
  two additional certificate programs. I am proficient in many technologies,
  including Python, Java, JavaScript, and SQL.
  <br><br>
  I enjoy learning foreign languages as a hobby. Feel free to check out some of
  my song translations on
  <a href="https://lyricstranslate.com/en/translator/pattystringbean">
  my Lyrics Translate page</a>!
